---

on:
  push:
  pull_request:
jobs:
  test:
    name: test on push or pull-request
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - id: lint
      name: Lint Code Base
      uses: github/super-linter@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - id: c-lint
      name: c-linter
      uses: ArtificialAmateur/clang-tidy-action@0.01
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - id: mkdir-build
      name: create build directory
      run: cmake -E make_directory build install
    - id: config
      name: configure build
      run: cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install ..
      working-directory: 'build'
    - id: build-release
      name: build release
      run: cmake --build . --config Release
      working-directory: 'build'
    - id: build-debug
      name: build debug
      run: cmake --build . --config Debug
      working-directory: 'build'
    - id: install-release
      name: install release
      run: |
          cmake --build . --target install
      working-directory: 'build'
# Disabled test, doesn't work on Ubuntu 20.04
#    - id: run-test-partition
#      name: run test_partition
#      run: sudo /bin/bash -c "PATH=${PATH}:${{ github.workspace}}/install/bin src/partrt/test/test_partition.py default -v"
    - id: run-ctest
      name: run ctest
      run: ctest
      working-directory: 'build'
    - id: build-packages
      name: build packages
      run: |
          cmake --build . --config Release --target package
      working-directory: 'build'

